// Evaluator for `Condition`. Runs per frame from UI paths, so the answer path is
// allocation-free: the leaf node IS the params record, indexed loops, depth by argument.
// FALSE is the answer to anything it cannot answer — hidden content is a bug report,
// wrongly revealed content is a spoiler or soft-lock the player cannot un-see.

import type { Condition, ConditionTest, Diagnostic, EvalCtx, QuestStatus } from "./types";
import { isId } from "./ids";
import { isFlagName, isObjectiveName, isQuestStatus } from "./state";

// Capped: a remote pack can nest as deep as it likes, and a deep tree is a stack
// overflow inside a frame. Deepest shipped condition is 3.
const MAX_DEPTH = 32;

/** Untrusted node: every field unknown until checked. */
interface CondView {
  readonly all?: unknown;
  readonly any?: unknown;
  readonly not?: unknown;
  readonly test?: unknown;
}

export class ConditionEvaluator {
  private readonly tests = new Map<string, ConditionTest>();
  private readonly diags: Diagnostic[] = [];
  private readonly reported = new Set<string>();
  // A REFUSAL, not the answer false: a plain false is invertible, so `not` around a
  // too-deep or malformed node would REVEAL gated content. Latches for the whole walk.
  // An unknown TEST is not a refusal — false composes, and a newer pack may be valid.
  private aborted = false;

  /** A later definition of the same name replaces the earlier — that is how tools stub. */
  define(name: string, fn: ConditionTest): void {
    this.tests.set(name, fn);
  }

  has(name: string): boolean {
    return this.tests.has(name);
  }

  get testNames(): readonly string[] {
    return [...this.tests.keys()].sort();
  }

  /** No `when` means always available — the common case. */
  evaluate(when: Condition | undefined, ctx: EvalCtx): boolean {
    if (when === undefined) {
      return true;
    }
    this.aborted = false;
    const value = this.node(when, ctx, 0);
    return this.aborted ? false : value;
  }

  private node(node: unknown, ctx: EvalCtx, depth: number): boolean {
    if (this.aborted) {
      return false;
    }
    if (depth > MAX_DEPTH) {
      this.aborted = true;
      this.reportOnce("depth", {
        severity: "error",
        code: "condition-too-deep",
        message: `condition nested deeper than ${MAX_DEPTH}; evaluated as false`,
        fix: "flatten the condition — nesting this deep is almost always generated by accident",
      });
      return false;
    }
    if (node === null || typeof node !== "object") {
      return this.badShape();
    }
    const c = node as CondView;

    // Leaf first: the common node, and every combinator bottoms out in one.
    if (typeof c.test === "string") {
      return this.leaf(c.test, node, ctx);
    }

    if (c.all !== undefined) {
      // Empty `all` is TRUE: adding a requirement may only narrow, so zero is widest.
      if (!Array.isArray(c.all)) {
        return this.badList("all");
      }
      for (let i = 0; i < c.all.length; i++) {
        if (!this.node(c.all[i], ctx, depth + 1)) {
          return false;
        }
      }
      return true;
    }

    if (c.any !== undefined) {
      // Empty `any` is FALSE: adding an alternative may only widen, so zero is narrowest.
      if (!Array.isArray(c.any)) {
        return this.badList("any");
      }
      for (let i = 0; i < c.any.length; i++) {
        if (this.node(c.any[i], ctx, depth + 1)) {
          return true;
        }
      }
      return false;
    }

    if (c.not !== undefined) {
      return !this.node(c.not, ctx, depth + 1);
    }

    return this.badShape();
  }

  private badShape(): boolean {
    this.aborted = true;
    this.reportOnce("shape", {
      severity: "error",
      code: "bad-condition",
      message: "a condition must be an object with `all`, `any`, `not` or `test`",
    });
    return false;
  }

  private leaf(name: string, params: unknown, ctx: EvalCtx): boolean {
    const fn = this.tests.get(name);
    if (fn === undefined) {
      // Once per NAME: this runs per frame, and a diagnostic per call is a leak.
      this.reportOnce(`test:${name}`, {
        severity: "error",
        code: "unknown-test",
        message: `unknown condition test "${name}"; evaluated as false`,
        field: "when.test",
        fix: "register it with defineTest(), or correct the spelling",
      });
      return false;
    }
    return fn(params as Readonly<Record<string, unknown>>, ctx);
  }

  // A malformed list is a REFUSAL, not the empty-list answer: broken hides content.
  private badList(key: "all" | "any"): boolean {
    this.aborted = true;
    this.reportOnce(`list:${key}`, {
      severity: "error",
      code: "bad-condition",
      message: `\`${key}\` must be an array of conditions; evaluated as false`,
      field: `when.${key}`,
    });
    return false;
  }

  private reportOnce(key: string, d: Diagnostic): void {
    if (this.reported.has(key)) {
      return;
    }
    this.reported.add(key);
    this.diags.push(d);
  }

  diagnostics(): readonly Diagnostic[] {
    return this.diags;
  }

  /** Clears the once-per-problem memory too, or a later pack loses its findings. */
  clearDiagnostics(): void {
    this.diags.length = 0;
    this.reported.clear();
  }
}

// Shipped tests. Bad params return false and report NOTHING — a per-frame path has
// no bounded way to complain; authoring mistakes belong to the load-time validator.

function pStr(params: Readonly<Record<string, unknown>>, key: string): string | null {
  const v = params[key];
  return typeof v === "string" ? v : null;
}

function pBool(params: Readonly<Record<string, unknown>>, key: string, dflt: boolean): boolean {
  const v = params[key];
  return typeof v === "boolean" ? v : dflt;
}

function pNum(params: Readonly<Record<string, unknown>>, key: string, dflt: number): number {
  const v = params[key];
  return typeof v === "number" && Number.isFinite(v) ? v : dflt;
}

// The tests every package may assume. No `all-of`/`any-of`: composition is the
// condition's SHAPE, and a second spelling means two trees to validate and render.
export function registerCoreTests(ev: ConditionEvaluator): void {
  /** `value` (default true) so the negative reads inline without a `not` wrapper. */
  ev.define("flag", (params, ctx) => {
    const name = pStr(params, "flag");
    if (name === null || !isFlagName(name)) {
      return false;
    }
    return ctx.state.flag(name) === pBool(params, "value", true);
  });

  // Exact status, not "at least": the statuses are not a ladder.
  ev.define("quest", (params, ctx) => {
    const quest = pStr(params, "quest");
    const status = params.status;
    if (quest === null || !isId(quest) || !isQuestStatus(status)) {
      return false;
    }
    return ctx.state.questStatus(quest) === (status as QuestStatus);
  });

  // Does NOT require the id to be loaded, or availability would depend on where
  // the player is standing.
  ev.define("discovered", (params, ctx) => {
    const id = pStr(params, "id");
    if (id === null || !isId(id)) {
      return false;
    }
    return ctx.state.discovered(id);
  });

  /** `atLeast` defaults to 1 — "touched at all", the boolean-objective case. */
  ev.define("progress", (params, ctx) => {
    const quest = pStr(params, "quest");
    const objective = pStr(params, "objective");
    if (quest === null || objective === null) {
      return false;
    }
    if (!isId(quest) || !isObjectiveName(objective)) {
      return false;
    }
    return ctx.state.progress(quest, objective) >= pNum(params, "atLeast", 1);
  });

  // For TOOLS: a valid stub, and `never` disables content in place without
  // dropping it from the graph.
  ev.define("always", () => true);
  ev.define("never", () => false);
}
